# Install dependencies.
install:
  - sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n

before_script:
  - state deploy shnewto/geta
# Run linting and tests.
script:
  - pytest

# Turn email notifications off.
notifications:
  email: false