language: python
python:
  - "3.6"

# Install dependencies.
install:
  - python3 -m pip install -r requirements.txt

# Run linting and tests.
script:
  - python3 -m pytest

# Turn email notifications off.
notifications:
  email: false
